spring:
  application:
    name: cluster-agent
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:10.245.1.233:8848}

#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: "jdbc:mysql://172.16.17.38:3306/testdb?useSSL=false"
#    username: "root"
#    password: "passwordA123$"
server:
  port: 8086
k8s:
  namespace: kube-test
  api: https://10.245.1.233:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik9oRUlMOXR3OHdFcjduUEx1VjFLTE94WlQ4Tkd2ZnRsX2NoM0REMEMzUWsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhcGlpbnZva2VyLXRva2VuIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImFwaWludm9rZXIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwNzE1MjIwMi01OGNkLTQ4YTEtODk2Mi03YTk3YzkzMDg2NjkiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YXBpaW52b2tlciJ9.LbjNXWHo76Y_A4JPU0qbTdjUlZ9tZDL76cXyE9Ap8ZSN6YHRzMLHReHaKnAI38uIWhlfCWITNTn6iLqtv8iMmeSpjbwi2FFfXo8MLmN_RmrAb529dXPrS8RPmdwlvZ2Y8MMqLW1VvvDH1mEF-uPxoeFi-G693G9cW3u_kwkTEnFBTBgab5-xPkAx0v9IJc8vYX31guUpdZ4bNpb3ijHglv4OM0H8OHuYlyBELOnGUpziIB39Vw_uDUblbjlSodRrnEGR7TC2ECqsXzc9d5pOtPS2o9hoj0LY12hjmKqAjhUrBLyhe1E2yKT65SG5zpsWmHgQPYoNqqOqdADVn3_UoQ