spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/admin/**