spring:
  application:
    name: refactorService
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDRS:10.245.1.233:8848}
      config:
        server-addr: ${NACOS_ADDRS:10.245.1.233:8848}
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: "jdbc:mysql://172.16.17.38:3306/testdb?useSSL=false"
#    username: "root"
#    password: "passwordA123$"
server:
  port: 8085
nacos:
  addr: 10.245.1.233:8848
clusterAgent:
  ipandPort: 10.245.1.233:8086
harbor:
  host: 10.245.1.233:5000
  project: testreposity
detector:
  ipandPort: 127.0.0.1:8099
refactor:
  configuration:
    templates:
      eureka-client: templates/eureka_client.yml
      eureka-server: templates/eureka_server.yml
      nacos-client: templates/nacos_client.yml
      config-server: templates/config_server.yml
      config-client: templates/config_client.yml
      gateway: templates/gateway.yml
  dependencies:
    eureka-server:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-starter-netflix-eureka-server
    eureka-client:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-starter-netflix-eureka-client
    spring-cloud:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-dependencies
      version: 2021.0.1
      type: pom
      scope: import
    spring-cloud-alibaba:
      groupId: com.alibaba.cloud
      artifactId: spring-cloud-alibaba-dependencies
      version: 2021.0.1.0
      type: pom
      scope: import
    nacos:
      groupId: com.alibaba.cloud
      artifactId: spring-cloud-starter-alibaba-nacos-discovery
    config-server:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-config-server
    config-client:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-starter-config
    bootstrap:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-starter-bootstrap
    gateway:
      groupId: org.springframework.cloud
      artifactId: spring-cloud-starter-gateway
