apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: root-ingress-role
rules:
  - apiGroups: ["networking.k8s.io"]  # 关联 Ingress 资源的 API 组
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: root-ingress-rolebinding
subjects:
  - kind: ServiceAccount
    name: default              # 这是指在指定命名空间中的 ServiceAccount
    namespace: kube-test       # 必须指定适当的命名空间
    apiGroup: ""               # 使用空字符串
roleRef:
  kind: ClusterRole
  name: root-ingress-role      # 关联到您之前定义的 ClusterRole
  apiGroup: rbac.authorization.k8s.io